### ISSUE TITLE
Support wasm-bindgen-cli

### ISSUE THREAD

**Issue by GalAster** [jetli/wasm-pack-action#6]
`wasm-bindgen-cli` also a commonly used library when using wasm toolkit.

`cargo install wasm-bindgen-cli` takes about 6 min, which takes up most of the ci time.

**Comment by jetli** [comment]
you mean executables from here? https://github.com/rustwasm/wasm-bindgen/releases

**Comment by jetli** [comment]
I made a new repo to do this: https://github.com/jetli/wasm-bindgen-action, working on it.

**Comment by jetli** [comment]
Finished and released to marketplace : https://github.com/marketplace/actions/wasm-bindgen-action
you can have a try
